### ISSUE TITLE
`boot target -h` clears target/ as well as showing help

### ISSUE THREAD

**Issue by HakimCassimallyBBC** [boot-clj/boot#585] opened 2017-02-10 14:09 UTC
e.g. 

```
$ boot build
... wait some time...
# Aha!  I wonder if I can preserve target/ to speed up the next build!

$ boot target -h
... some help output

$ find target/   # oh noes, it all got deleted!
```

In general, asking for help shouldn't also do things, so this feels like a bug.

**Comment by alandipert** [comment] 2017-03-08 06:30
Agreed: `-h` shouldn't do anything. A PR would be most welcome.

**Comment by DonyorM** [comment] 2017-04-30 22:07
I'm going to try and take this issue on. Would anyone be willing to point to me the function which clears out the target folder?

**Comment by DonyorM** [comment] 2017-05-30 22:39
I am no longer seeing this behavior on my machine. Is this issue fixed?

**Comment by martinklepsch** [comment] 2017-12-21 22:31
Also could not reproduce this issue, closing.

**Closed by martinklepsch** 2017-12-21 22:31 UTC
Labels: Enhancement, pr-most-welcome
