### ISSUE TITLE
CLI-invoked dependencies can fail when build.boot present

### ISSUE THREAD

**Issue by pandeiro** [boot-clj/boot#103] opened 2015-01-27 19:46 UTC
Running `boot -d somedep/foo sometask` from a directory with a `build.boot` which does **not** set up `somedep/foo` as a dependency results in a FileNotFoundException. Apparently (and understandably) Boot looks for the dependency in question on the classpath created by `build.boot`.

This is admittedly an edge case but can happen where standalone (ie, project-independent) tasks or scripts are involved.

Apologies if this is the expected behavior; I couldn't find this case covered in the docs.

**Comment by micha** [comment] 2015-01-27 19:53
I think the problem is that the `build.boot` file should use something like this:

```clojure
(set-env! :dependencies #(into % '[[foo/bar "1.2.3"] ...]) ...)
```

instead of:

```clojure
(set-env! :dependencies '[[foo/bar "1.2.3"] ...])
```

because the first merges deps, while the second overwrites them.

**Comment by pandeiro** [comment] 2015-01-27 21:24
@micha I guess the case I am describing is one in which the presence of `build.boot` in the directory is entirely incidental, ie it has nothing to do with the Boot task/script being performed, and hence changing it is not really a solution. Does that make sense?

**Comment by micha** [comment] 2015-01-27 23:46
Ah, in that case you can use the `-B`, `--no-boot-script` option:

```
boot -B -d somedep/foo sometask
```

This will just skip reading the `build.boot` file.

**Comment by micha** [comment] 2015-01-27 23:50
I guess the expectation is that command line arguments override settings in `build.boot`, which makes sense. Perhaps there is something that can be done.

**Comment by micha** [comment] 2015-01-28 00:04
Are you sure it doesn't work? I just did the following:

_build.boot_
```clojure
(set-env! :dependencies '[[clj-http  "1.0.1"]])
```

_in a terminal_
```
$ boot repl
```
```clojure
nREPL server started on port 45520 on host 0.0.0.0 - nrepl://0.0.0.0:45520
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.7.0_72-b14
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
boot.user=> (require 'clj-http.client)
nil
boot.user=> (require 'tailrecursion.warp)
java.io.FileNotFoundException: Could not locate tailrecursion/warp__init.class or tailrecursion/warp.clj on classpath:
```
_again in the terminal_
```
$ boot -d tailrecursion/warp repl
```
```clojure
nREPL server started on port 45520 on host 0.0.0.0 - nrepl://0.0.0.0:45520
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.7.0_72-b14
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
boot.user=> (require 'clj-http.client)
nil
boot.user=> (require 'tailrecursion.warp)
nil
```

**Comment by pandeiro** [comment] 2015-01-28 00:07
Re: example above, can you try with a task only defined via `tailrecursion/warp`?

**Comment by pandeiro** [comment] 2015-01-28 00:08
To the larger point, re: your comments above:

I'm not sure if the expected, least-surprises behavior would be *overriding* or *merging* the dep(s) specified on the command line into the environment specified through `build.boot`, when one exists.

I can imagine pros and cons and potential use cases for both. Maybe it's something that should be thought about.

**Comment by micha** [comment] 2015-01-28 00:11
We've always gone with "do what you mean" with boot. That is to say, if the user makes a `build.boot` file that contains `(set-env! :dependencies '[[foo/bar "1.2.3"]])` then it's because that's what they meant to do. They are intentionally replacing the existing dependencies. If they really meant to merge them then they would have done `(set-env! :dependencies #(into % '[[foo/bar "1.2.3"]]))`. If we force-merge then the user can no longer override them.

**Comment by pandeiro** [comment] 2015-01-28 00:16
@micha Makes sense as the default, you're right.

**Comment by micha** [comment] 2015-01-28 00:17
I see the problem now. The task is configuring its pod using the core pod as the basis, meaning it just adds dependencies to whatever the core pod has. However, if the `build.boot` file overwrites your `-d` dependencies then the pod the task creates won't have access to the task's jars, and you'll see the error:

```
$ boot -d pandeiro/boot-http -s boot serve
```
```
<< stopping Jetty... >>
             clojure.lang.ExceptionInfo: java.io.FileNotFoundException: Could not locate pandeiro/boot_http/impl__init.class or pandeiro/boot_http/impl.clj on classpath: 
    data: {:file "../tmp/boot.user2459163442543943717.clj", :line 15}
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Could not locate pandeiro/boot_http/impl__init.class or pandeiro/boot_http/impl.clj on classpath: 
          java.io.FileNotFoundException: Could not locate pandeiro/boot_http/impl__init.class or pandeiro/boot_http/impl.clj on classpath: 
                                ...                                        
               clojure.core/load/fn                          core.clj: 5641
                  clojure.core/load                          core.clj: 5640
                                ...                                        
              clojure.core/load-one                          core.clj: 5446
           clojure.core/load-lib/fn                          core.clj: 5486
              clojure.core/load-lib                          core.clj: 5485
                                ...                                        
                 clojure.core/apply                          core.clj:  626
             clojure.core/load-libs                          core.clj: 5524
                                ...                                        
                 clojure.core/apply                          core.clj:  626
               clojure.core/require                          core.clj: 5607
                                ...                                        
                  pod$eval52.invoke                    NO_SOURCE_FILE      
                                ...                                        
                  clojure.core/eval                          core.clj: 2927
                  boot.pod/eval-in*                           pod.clj:  203
                                ...                                        
                  boot.pod/eval-in*                           pod.clj:  206
    pandeiro.boot-http/eval66/fn/fn                     boot_http.clj:   42
                                ...                                        
                 clojure.core/deref                          core.clj: 2200
 pandeiro.boot-http/eval66/fn/fn/fn                     boot_http.clj:   66
                boot.core/run-tasks                          core.clj:  623
                                ...                                        
               boot.user/eval218/fn  boot.user2459163442543943717.clj:   17
clojure.core/binding-conveyor-fn/fn                          core.clj: 1910
                                ...
```
```                                        
$ boot -B -d pandeiro/boot-http -s boot serve
```
```                                                                                                             
2015-01-27 19:14:22.665:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-01-27 19:14:22.689:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:3000
<< started Jetty on http://localhost:3000 >>
<< stopping Jetty... >>
```

**Comment by pandeiro** [comment] 2015-01-28 00:22
Yep, that's it.

For my own use, I have no problem invoking with `-B` and this isn't urgent nor super important.

But I do think most users would assume that a dependency included with `-d` should be able to fire off its task as normal, independently of the existence of a `build.boot`. What do you think?

**Comment by micha** [comment] 2015-01-28 00:26
I think the real solution is to use the update-in style of setting dependencies in our `build.boot` files if we want `-d` to work the way you describe. We could change the demos and examples to show that.

**Comment by pandeiro** [comment] 2015-01-28 00:36
@micha I think I muddied the waters a bit with my question about override vs. merge above, sorry. From the "merge", `build.boot`-based perspective, yes, absolutely, the update-in approach is the way.

Do you think there's anything though to the idea that boot tasks or scripts should be able to specify deps and invoke tasks w/o interference from an existing `build.boot`, ie the override scenario you mentioned above? Or is this a super marginal case (besides the HTTP server :) ?

**Comment by micha** [comment] 2015-01-28 01:30
Do you mean that tasks should be able to override the `build.boot`?

**Comment by pandeiro** [comment] 2015-01-28 01:47
Not tasks, CLI args. Specifically -d.

**Comment by micha** [comment] 2015-01-28 01:58
Perhaps we need a `env` task or something, like:

```
$ boot env -d pandeiro/boot-http serve
```

**Comment by micha** [comment] 2015-01-29 02:26
Perhaps the solution is to promote using the new `merge-env!` function in `build.boot` instead of `set-env!`. (See 5ef99a272643c8ed7c70e37285f08b24bde401b6.) Then the `build.boot` env settings will be merged into the settings specified on the command line, and the user still has the option to use `set-env!` if they actually want to override `--dependency` options from the command line.

**Comment by lypanov** [comment] 2015-01-29 07:08
I ran into this one also last night. For me it was far from expected behaviour.

**Comment by pandeiro** [comment] 2015-01-29 11:27
@micha From the point of view of the `build.boot` authors, I think there
are ample options to deal with this kind of scenario.

But from the perspective of Boot task users, these mechanisms are kind of
orthogonal to the issue.

I do think the -B flag addresses that issue partly, bit the question
remains of what the expected, "do what I mean" behavior should be when
using the -d option. That should be defined and added to the docs.

**Closed** 2015-01-29 15:48 UTC
