### ISSUE TITLE
Boot build stalls on heroku

### ISSUE THREAD

**Issue by taylorSando** [boot-clj/boot#170] opened 2015-03-20 00:35 UTC
Not sure if this should go here, or with boot-cljs, but I'm having a problem getting boot to play nicely with heroku.

https://github.com/taylorSando/boot-heroku-test

I made a custom buildpack, the one that you guys list in the wiki projects doesn't seem to work.

It tries to build, but it gets stuck on compiling main.js

Basically bin/build causes **boot package** to run

Then the Procfile should run the created jar.

**Comment by alandipert** [comment] 2015-03-20 04:38
Happy to let this hang out here, but you may consider posting also to http://hoplon.discoursehosting.net/ which probably gets more attention.

In the meantime I'll try to reproduce, it would be nice to have a working Heroku setup for sure.

**Comment by taylorSando** [comment] 2015-03-20 04:57
You should be able to use https://github.com/taylorSando/boot-heroku-test

It's basically the om/cljx boot example.  I can run it locally by doing **boot package** and then running the resulting jar file.

Make sure you use my heroku buildpack, because the other one doesn't seem to work properly.

**Comment by micha** [comment] 2015-03-20 14:20
Looks like it might be a memory issue. [The buildpack](https://github.com/taylorSando/heroku-buildpack-boot/blob/master/bin/compile#L104) seems to be specifying `-Xmx400M`, which isn't enough to run the google closure compiler with advanced optimizations, I don't think.

**Comment by micha** [comment] 2015-03-20 14:44
Also see pandeiro/heroku-buildpack-boot#4 for a way to pull the latest version of `boot.sh` automatically (issues are disabled for [taylorSando/boot-heroku-test][1] or I'd reference it there).

[1]: https://github.com/taylorSando/boot-heroku-test

**Comment by micha** [comment] 2015-04-05 16:22
Has this been resolved? Can we close the issue?

**Closed** 2015-04-06 03:44 UTC
Labels: blocked, help wanted, question
