### ISSUE TITLE
Not compatible with Cygwin?

### ISSUE THREAD

**Issue by dmos62** [boot-clj/boot#30] opened 2014-12-08 08:36 UTC
Can't seem to get it running under Cygwin. I shall try and illustrate by copy pasting commands from mintty:

    $ ls -l boot.sh
    -rwxr-xr-x+ 1 Domas None 7012598 Dec  7 21:23 boot.sh

    $ boot.sh
    Error: Unable to access jarfile /home/Domas/bin/boot.sh

    $ java -jar boot.sh -V
    #https://github.com/boot-clj/boot
    #Mon Dec 08 10:27:04 EET 2014
    BOOT_CLOJURE_VERSION=1.6.0
    BOOT_VERSION=2.0.0-pre28

Now here comes the crash (?). I will run the repl, but it will not respond to any input, I will ultimately Ctrl-c:

    Domas@DomoHP-Win81 ~/bin
    $ java -jar boot.sh repl
    nREPL server listening: 0.0.0.0:49542
    REPL-y 0.3.4, nREPL 0.2.4
    Clojure 1.6.0
    Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14
            Exit: Control+D or (exit) or (quit)
        Commands: (user/help)
            Docs: (doc function-name-here)
                  (find-doc "part-of-name-here")
    Find by Name: (find-name "part-of-name-here")
          Source: (source function-name-here)
         Javadoc: (javadoc java-object-or-class-here)
        Examples from clojuredocs.org: [clojuredocs or cdoc]
                  (user/clojuredocs name-here)
                  (user/clojuredocs "ns-here" "name-here")
    boot.user=> (+ 2 2)

    $ (+ 2 2)
    -bash: +: command not found

Some additional information below. Notably I am using a Windows Java installation, which has not caused problems running sbt or leiningen by the way.

    $ java -version
    java version "1.7.0_71"
    Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

    $ javac -version
    javac 1.7.0_71

    $ which java
    /cygdrive/c/Program Files/Java/jdk1.7.0_71/bin/java

    $ which javac
    /cygdrive/c/Program Files/Java/jdk1.7.0_71/bin/javac

    $ echo $TERM
    xterm-256color

**Comment by schmir** [comment] 2015-02-01 22:02
I can confirm the issue.

It looks like cygwin's mintty has many problems with windows console applications:

https://github.com/joyent/node/issues/6459
https://code.google.com/p/mintty/issues/detail?id=56
https://code.google.com/p/mintty/issues/detail?id=244

Judging from the last link, the repl client may try to check if System/console is nil and refuse to start.

**Comment by micha** [comment] 2015-03-05 02:06
@dmos62 Can you use the leiningen repl client in Cygwin? Or does that result in the same problem?

**Comment by dmos62** [comment] 2015-03-05 11:28
`lein repl` works fine; however, interestingly, `lein trampoline repl` has the same problem. More specifically `lein trampoline repl` stopped responding after the first run, `lein clean` does not help.

**Comment by schmir** [comment] 2015-03-09 20:12
see https://github.com/technomancy/leiningen/issues/850

**Comment by dmos62** [comment] 2015-03-10 08:08
Opened an issue https://github.com/technomancy/leiningen/issues/1852

**Comment by micha** [comment] 2015-03-11 00:37
@dmos62 Can you try the `stty` and system properties workarounds as described in technomancy/leiningen#850 and see if that will fix `boot.sh` in Cygwin? Thanks!

**Comment by dmos62** [comment] 2015-03-12 09:15
The workaround works:

    ~/bin % cat boot
    #!/bin/bash
    stty -icanon min 1 -echo
    java \
          -Djline.terminal=jline.UnixTerminal \
          -jar boot.sh "$@"
    stty icanon echo

First(?) session on Cygwin:

    ~/bin % boot repl
    nREPL server listening: 0.0.0.0:63406
    REPL-y 0.3.4, nREPL 0.2.4
    Clojure 1.6.0
    Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14
            Exit: Control+D or (exit) or (quit)
        Commands: (user/help)
            Docs: (doc function-name-here)
                  (find-doc "part-of-name-here")
    Find by Name: (find-name "part-of-name-here")
          Source: (source function-name-here)
        Javadoc: (javadoc java-object-or-class-here)
        Examples from clojuredocs.org: [clojuredocs or cdoc]
                  (user/clojuredocs name-here)
                  (user/clojuredocs "ns-here" "name-here")
    boot.user=> (+ 2 2)
    4
    boot.user=> "hello"
    "hello"
    boot.user=>

**Comment by micha** [comment] 2015-03-12 17:08
Ok awesome, I'll work something out for this. Hopefully it won't need to be _too_ ugly. I'll push to a branch so you can test it before it gets merged into master, okay?

**Comment by dmos62** [comment] 2015-03-12 17:19
Sounds good.

**Comment by micha** [comment] 2015-03-15 17:38
@dmos62 Can you please verify that this does in fact work? Thanks :)

**Comment by dmos62** [comment] 2015-03-16 11:23
@micha I verify :) though an interesting echo effect appeared, but that's another story.

    % bin/boot.sh repl                                      
    nREPL server started on port 59805 on host 127.0.0.1 - nrepl://127.0.0.1:59805
    REPL-y 0.3.5, nREPL 0.2.7
    Clojure 1.6.0
    Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14
    [omited]
    boot.user=> (+ 2 2)
    (+ 2 2)
    4
    boot.user=> "hello"
    "hello"
    "hello"
    boot.user=>

**Comment by micha** [comment] 2015-03-16 13:20
That looks like the `stty -echo` wasn't working for some reason?

**Comment by dmos62** [comment] 2015-03-16 16:57
Yes. The [shell calls](https://github.com/boot-clj/boot/commit/536d0734b38fa8297623c3fa96f5fa4a9021cfef#diff-d603b3b161a6b46514002dba5c359837R61) seem to be exactly the same like in the workaround script, yet when I wrap the latest boot in that script the echo disappears.

**Closed** 2015-11-09 15:36 UTC
Labels: blocked, bug, help wanted, windows, wontfix
