### ISSUE TITLE
AccessDeniedException on W7 when running boot.dev

### ISSUE THREAD

**Issue by sveri** [boot-clj/boot#76] opened 2015-01-08 10:19 UTC
To reproduce:
1. Clone: https://github.com/Deraen/saapas
2. run boot dev in the folder where you cloned the example project to

This exception will occur:

```
c:\Users\sveri\IdeaProjects\saapass>boot dev
<< started reload server on ws://localhost:50592 >>
Adding cljsjs/common/react-externs.ext.js to fileset
Adding cljsjs/development/react.inc.js to fileset
Starting file watcher (CTRL-C to quit)...

←[1;31mjava.nio.file.AccessDeniedException←[m: ←[31mC:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\saapass\37k\rcesf6\saapas\main.clj -> C:\Users\s
veri\.boot\tmp\Users\sveri\IdeaProjects\saapass\37k\-7kd6cy\09ebebee8d000dd380fb0d1e968ceb48←[m
         ←[1mfile←[m: "C:\\Users\\sveri\\.boot\\tmp\\Users\\sveri\\IdeaProjects\\saapass\\37k\\rcesf6\\saapas\\main.clj"
    ←[1motherFile←[m: "C:\\Users\\sveri\\.boot\\tmp\\Users\\sveri\\IdeaProjects\\saapass\\37k\\-7kd6cy\\09ebebee8d000dd380fb0d1e968ceb48"
←[37msun.nio.fs.WindowsException.translateToIOException←[m  ←[32m           WindowsException.java:   83←[m
  ←[37msun.nio.fs.WindowsException.rethrowAsIOException←[m  ←[32m           WindowsException.java:   97←[m
   ←[37msun.nio.fs.WindowsFileSystemProvider.createLink←[m  ←[32m  WindowsFileSystemProvider.java:  608←[m
                                               ...←[m  ←[32m                                      ←[m
                               ←[33mboot.file/←[1;33mhard-link←[m  ←[32m                        file.clj:  107←[m
                       ←[33mboot.file/←[1;33mcopy-with-lastmod←[m  ←[32m                        file.clj:  120←[m
                    ←[33mboot.tmpdir.TmpFileSet/←[1;33mcommit!←[m  ←[32m                      tmpdir.clj:   69←[m
                                 ←[33mboot.core/←[1;33mcommit!←[m  ←[32m                        core.clj:  309←[m
              ←[33mboot.task.built-in/fn/fn/fn/fn/fn/←[1;33mfn←[m  ←[32m                    built_in.clj:  162←[m
                 ←[33mboot.task.built-in/fn/fn/fn/fn/←[1;33mfn←[m  ←[32m                    built_in.clj:  162←[m
                    ←[33mboot.task.built-in/fn/fn/fn/←[1;33mfn←[m  ←[32m                    built_in.clj:  159←[m
               ←[33mcljsjs.boot-cljsjs/eval294/fn/fn/←[1;33mfn←[m  ←[32m                 boot_cljsjs.clj:   30←[m
                               ←[33mboot.core/←[1;33mrun-tasks←[m  ←[32m                        core.clj:  597←[m
                                               ...←[m  ←[32m                                      ←[m
                             ←[33mboot.user/eval1075/←[1;33mfn←[m  ←[32mboot.user6390581289017634711.clj:   17←[m
               ←[33mclojure.core/binding-conveyor-fn/←[1;33mfn←[m  ←[32m                        core.clj: 1910←[m
                                               ...←[m  ←[32m                                      ←[m
Elapsed time: 0,246 sec

Compiling {less}... 2 changed files.
Compiling cljx... 1 changed files.
nREPL server started on port 50645 on host 0.0.0.0 - nrepl://0.0.0.0:50645
Compiling boot-cljs-main.js...
Starting web server on port 10555
Elapsed time: 32,134 sec
```

The weird thing is, when I did that the first time it worked, but not once after it.
I deleted the .boot folder in \users\sveri. I deleted the project and cloned it again, I even rebooted, no success so far. I also ran the command line as administrator, which didn't help either.

I have the boot.exe "installed" in \Windows\System32 as suggested.
This is the output of: boot -h
Boot App Version: 2.0.0-rc4
Boot Lib Version: 2.0.0-rc5
Clojure Version:  1.6.0
JDK v1.8.0_25-b18

**Comment by micha** [comment] 2015-03-05 02:28
Is this still an issue with `2.0.0-rc11`?

**Comment by sveri** [comment] 2015-03-05 08:03
A first quick test works. However, I will test it more thouroughly in the next days, so please leave it open for now.

**Comment by micha** [comment] 2015-03-05 15:37
Great, thanks for the update!

**Comment by sveri** [comment] 2015-03-05 18:44
Hi,

I tried to integrate boot into a current project. While it started fairly good it failed fast. This is the branch of the project: <https://github.com/sveri/siwf/tree/boot>.
I was able to run `boot dev` and start everything. Unluckily I forgot to include the resources folder first which resulted in a runtime error in selmer.  
Adding the resource path and starting up boot dev again resulted in the first exception (not sure if it was accessdenied or file not found.  
I had to delete %userhome%/.boot folder and some generated folders in my project + the target folder of the proejct and the generated cljs files.

Then I got it running again, but when compiling the cljs I get this output:  

Compiling ClojureScript.
ERROR deleting #<File C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri\siwf> #<IOException java.io.IOException: Couldn't d
lete C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri\siwf>
ERROR deleting #<File C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri> #<IOException java.io.IOException: Couldn't delete
C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri>
ERROR deleting #<File C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de> #<IOException java.io.IOException: Couldn't delete C:\Us
rs\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de>
java.nio.file.FileAlreadyExistsException: C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri\siwf\boot.clj -> C:\Users\sveri
.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-7kd6cy\d583a7936c950bc428ab2ad1deada584
         file: "C:\\Users\\sveri\\.boot\\tmp\\Users\\sveri\\IdeaProjects\\siwf\\7uo\\-p9hf6h\\de\\sveri\\siwf\\boot.clj"
    otherFile: "C:\\Users\\sveri\\.boot\\tmp\\Users\\sveri\\IdeaProjects\\siwf\\7uo\\-7kd6cy\\d583a7936c950bc428ab2ad1deada584"
sun.nio.fs.WindowsException.translateToIOException             WindowsException.java:   81
  sun.nio.fs.WindowsException.rethrowAsIOException             WindowsException.java:   97
   sun.nio.fs.WindowsFileSystemProvider.createLink    WindowsFileSystemProvider.java:  608
                                               ...
                               boot.file/hard-link                          file.clj:  112
                       boot.file/copy-with-lastmod                          file.clj:  125
                    boot.tmpdir.TmpFileSet/commit!                        tmpdir.clj:   69
                                 boot.core/commit!                          core.clj:  361
               adzerk.boot-reload/eval423/fn/fn/fn                   boot_reload.clj:   83
              boot.task.built-in/fn/fn/fn/fn/fn/fn                      built_in.clj:  172
                 boot.task.built-in/fn/fn/fn/fn/fn                      built_in.clj:  172
                    boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  169
                               boot.core/run-tasks                          core.clj:  669
                                               ...
                            boot.user/eval23047/fn  boot.user1846110738069607899.clj:   17
               clojure.core/binding-conveyor-fn/fn                          core.clj: 1910
                                               ...
Elapsed time: 0.937 sec

Writing main.cljs.edn...
Compiling boot-cljs-main.js...
Elapsed time: 2.538 sec

Writing main.cljs.edn...
ERROR deleting #<File C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri\siwf\components> #<IOException java.io.IOException:
Couldn't delete C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri\siwf\components>
ERROR deleting #<File C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri\siwf> #<IOException java.io.IOException: Couldn't d
lete C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri\siwf>
ERROR deleting #<File C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri> #<IOException java.io.IOException: Couldn't delete
C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de\sveri>
ERROR deleting #<File C:\Users\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de> #<IOException java.io.IOException: Couldn't delete C:\Us
rs\sveri\.boot\tmp\Users\sveri\IdeaProjects\siwf\7uo\-p9hf6h\de>
Compiling boot-cljs-main.js...
Elapsed time: 2.936 sec

Writing main.cljs.edn...
Compiling boot-cljs-main.js...
Elapsed time: 3.060 sec

**Comment by micha** [comment] 2015-03-06 23:37
The output looks strange&mdash;the error should be of the format

```
ERROR deleting <path> <exception>
```

What is the `# #` in the spot where the path should be? And the exception should have a full message, at least, shouldn't it? [The relevant code is here](https://github.com/boot-clj/boot/blob/2.0.0-rc11/boot/pod/src/boot/file.clj#L37).

**Comment by micha** [comment] 2015-03-06 23:40
Whoops, nevermind, I reformatted as a code block and now can see all. I think github was interpreting the `<` and `>` in there as HTML tag delimiter thingys.

**Comment by micha** [comment] 2015-03-11 00:41
@sveri Can you please try with `master` and see if my fix for #160 helps at all?

**Comment by sveri** [comment] 2015-03-11 08:11
Hi, 

I can do that, but it may take some days, not sure when I have enough time to follow up.

**Comment by sveri** [comment] 2015-03-11 08:21
Ok, it seems I cannot, running `make deps` produces this error:

    $ make deps
    FIND: Parameterformat falsch
    FIND: Parameterformat falsch
    FIND: Parameterformat falsch
    FIND: Parameterformat falsch
    FIND: Parameterformat falsch
    FIND: Parameterformat falsch
    make: F▒r das Ziel ▒deps▒ ist nichts zu tun.

In windows cmd line as well as in cygwin command line. Parameterformat falsch means something like: wrong parameter format.

**Comment by TGThorax** [comment] 2015-12-29 03:34
While trying the [moderncljs tutorials on ClojureScript](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-02.md) I got the same exception, as well as a `java.util.concurrent.ExecutionException` when evaluating `boot serve -d target watch cljs` with boot version 2.5.3. This exception does not occur with boot version 2.4.2. In version 2.5.3 it was solved by adding `BOOT_EMIT_TARGET=no`, to the boot.properties file,  and using `boot serve watch cljs target` instead.

As for the project as linked by @sveri the following errors exceptions occur for `boot dev`:

    Compiling {less}... 2 changed files.
    java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Use
    rs\Laurens\.boot\cache\tmp\TEMP\saapas\2q4\-grrwi1\css/
       index: 2
       input: "C:\\Users\\Laurens\\.boot\\cache\\tmp\\TEMP\\saapas\\2q4\\-grrwi1\\css/"

      reason: "Illegal character in opaque part"
   less4clj.cor
    e/join-url                       core.clj:   26
                                                         less4clj.core/custom-less
    -source/fn                       core.clj:   69
            less4clj.core.proxy$com.github.sommeri.less4j.LessSource$ff19274a.rela
    tiveSource
         com.github.sommeri.less4j.core.compiler.stages.SingleImportSolver.importE
    ncountered        SingleImportSolver.java:   78
    com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.importIntoP
    laceholder     ImportsAndScopeSolver.java:   65
     com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNes
    tedImports     ImportsAndScopeSolver.java:   49
     com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNes
    tedImports     ImportsAndScopeSolver.java:   44
    com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.buildImpor
    tsAndScope     ImportsAndScopeSolver.java:   38
       com.github.sommeri.less4j.core.compiler.LessToCssCompiler.resolveImportsAnd
     References         LessToCssCompiler.java:   95
                      com.github.sommeri.less4j.core.compiler.LessToCssCompiler.co
    mpileToCss         LessToCssCompiler.java:   47
                           com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler
    .doCompile  ThreadUnsafeLessCompiler.java:  115
                             com.github.sommeri.less4j.core.ThreadUnsafeLessCompil
     er.compile  ThreadUnsafeLessCompiler.java:   85
                                  com.github.sommeri.less4j.core.DefaultLessCompil
    er.compile       DefaultLessCompiler.java:   56
                                                                  less4clj.core/le
      ss-compile                       core.clj:  138
                                                          less4clj.core/less-compi
    le-to-file                       core.clj:  153
                                                                          clojure.
    core/apply                       core.clj:  630
                                                                       boot.pod/ev
    al-fn-call                        pod.clj:  294
                                                                           boot.po
    d/call-in*                        pod.clj:  315

**Comment by TGThorax** [comment] 2015-12-29 03:51
While trying the [moderncljs tutorials on ClojureScript](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-02.md) I got the same exception, as well as a `java.util.concurrent.ExecutionException` when evaluating `boot serve -d target watch cljs` with boot version 2.5.3. This exception does not occur with boot version 2.4.2. In version 2.5.3 it was solved by adding `BOOT_EMIT_TARGET=no`, to the boot.properties file, and using `boot serve watch cljs target` instead.

As for the project as linked by @sveri, the following errors exceptions occur for `boot dev`:

    Compiling {less}... 2 changed files.
    java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\TGThorax\.boot\cache\tmp\TEMP\saapas\2q4\-grrwi1\css/
       index: 2
       input: "C:\\Users\\TGThorax\\.boot\\cache\\tmp\\TEMP\\saapas\\2q4\\-grrwi1\\css/"
    reason: "Illegal character in opaque part"
       ...
    less4clj.core/join-url                       core.clj:   26
    less4clj.core/custom-less-source/fn                       core.clj:   69
    less4clj.core.proxy$com.github.sommeri.less4j.LessSource$ff19274a.relativeSource
    com.github.sommeri.less4j.core.compiler.stages.SingleImportSolver.importEncountered        SingleImportSolver.java:   78
    com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.importIntoPlaceholder     ImportsAndScopeSolver.java:   65
    com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNestedImports     ImportsAndScopeSolver.java:   49
    com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.solveNestedImports     ImportsAndScopeSolver.java:   44
    com.github.sommeri.less4j.core.compiler.stages.ImportsAndScopeSolver.buildImportsAndScope     ImportsAndScopeSolver.java:   38
    com.github.sommeri.less4j.core.compiler.LessToCssCompiler.resolveImportsAndReferences         LessToCssCompiler.java:   95
    com.github.sommeri.less4j.core.compiler.LessToCssCompiler.compileToCss         LessToCssCompiler.java:   47
    com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler.doCompile  ThreadUnsafeLessCompiler.java:  115
    com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler.compile  ThreadUnsafeLessCompiler.java:   85
    com.github.sommeri.less4j.core.DefaultLessCompiler.compile       DefaultLessCompiler.java:   56
        ...
    less4clj.core/less-compile                       core.clj:  138
    less4clj.core/less-compile-to-file                       core.clj:  153
        ...
    clojure.core/apply                       core.clj:  630
    boot.pod/eval-fn-call                        pod.clj:  294
    boot.pod/call-in*                        pod.clj:  315
        ...
    boot.pod/call-in*                        pod.clj:  318
    deraen.boot-less/eval595/fn/fn/fn                  boot_less.clj:   44
    boot.task.built-in/fn/fn/fn/fn/fn/fn                   built_in.clj:  264
    boot.task.built-in/fn/fn/fn/fn/fn                   built_in.clj:  264
    boot.task.built-in/fn/fn/fn/fn                   built_in.clj:  261
    boot.core/run-tasks                       core.clj:  791
    boot.core/boot/fn                       core.clj:  801
    clojure.core/binding-conveyor-fn/fn                       core.clj: 1916
       ...

**Comment by Deraen** [comment] 2015-12-29 13:41
@TGThorax That problem is probably caused by boot-less/less4clj.

**Comment by martinklepsch** [comment] 2017-12-22 12:32
@sveri @TGThorax this issue is pretty old and lots has changed in the meantime, would you mind giving this another spin with `2.7.2`? I unfortunately don't have access to a Windows machine to test.

**Comment by sveri** [comment] 2017-12-22 13:12
I just tried to reproduce it on W7 system and that specific case seems
to work as in "it recompiles the changes made on backend and frontend
side". Unfortunately I cannot test it any further for now.



On Fri, Dec 22, 2017, at 1:32 PM, Martin Klepsch wrote:
> @sveri[1] @TGThorax[2] this issue is pretty old and lots has changed
> in the meantime, would you mind giving this another spin with 2.7.2? I
> unfortunately don't have access to a Windows machine to test.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 


Links:

  1. https://github.com/sveri
  2. https://github.com/tgthorax
  3. https://github.com/boot-clj/boot/issues/76#issuecomment-353589667

**Comment by martinklepsch** [comment] 2017-12-22 13:21
Alright thanks for the quick smoke test @sveri, much appreciated. I'll close this for now but if anyone gets to do more testing and finds issues, feel free to reopen/create a new issue.

**Closed by martinklepsch** 2017-12-22 13:21 UTC
Labels: blocked, Bug, Windows
